version: '3.8'

services:
  application:
    image: php:8.4-fpm
    container_name: php-fpm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony-network
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libpq-dev &&
        docker-php-ext-install pdo_pgsql &&
        php-fpm
      "

  database:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_DB: music_service
      POSTGRES_USER: music_service_db_user
      POSTGRES_PASSWORD: music_service_db_pass
    ports:
      - "5436:5432"
    networks:
      - symfony-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge